-- MASTER MIGRATION FOR SUPABASE
-- Generated: 2026-05-03 07:41:43

SET session_replication_role = 'replica';

-- Supabase Schema for Rumah Laundry (No Records)
-- Run this in Supabase SQL Editor first

-- Disable triggers and foreign key constraints temporarily


-- Drop existing tables
DROP TABLE IF EXISTS "transaction_details" CASCADE;
DROP TABLE IF EXISTS "transactions" CASCADE;
DROP TABLE IF EXISTS "services" CASCADE;
DROP TABLE IF EXISTS "users" CASCADE;

-- Table structure for users
CREATE TABLE "users" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "name" text NOT NULL,
  "email" text NOT NULL UNIQUE,
  "email_verified_at" timestamp with time zone NULL,
  "password" text NOT NULL,
  "role" text NOT NULL DEFAULT 'user',
  "phone" text NULL,
  "whatsapp" text NULL,
  "address" text NULL,
  "latitude" decimal(10,7) NULL,
  "longitude" decimal(10,7) NULL,
  "remember_token" text NULL,
  "created_at" timestamp with time zone DEFAULT now(),
  "updated_at" timestamp with time zone DEFAULT now()
);

-- Table structure for services
CREATE TABLE "services" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "name" text NOT NULL,
  "category" text NOT NULL DEFAULT 'Umum',
  "price" decimal(10,2) NOT NULL,
  "unit" text NOT NULL DEFAULT 'kg',
  "description" text NULL,
  "created_at" timestamp with time zone DEFAULT now(),
  "updated_at" timestamp with time zone DEFAULT now()
);

-- Table structure for transactions
CREATE TABLE "transactions" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "user_id" bigint NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
  "invoice_code" text NOT NULL UNIQUE,
  "total_price" decimal(15,2) NOT NULL DEFAULT 0.00,
  "status" text NOT NULL DEFAULT 'baru',
  "address" text NULL,
  "phone" text NULL,
  "payment_method" text NULL,
  "delivery_type" text NULL,
  "created_at" timestamp with time zone DEFAULT now(),
  "updated_at" timestamp with time zone DEFAULT now(),
  CONSTRAINT "transactions_status_check" CHECK ("status" IN ('baru','cuci','kering','setrika','selesai','diambil'))
);

-- Table structure for transaction_details
CREATE TABLE "transaction_details" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "transaction_id" bigint NOT NULL REFERENCES "transactions"("id") ON DELETE CASCADE,
  "service_id" bigint NOT NULL REFERENCES "services"("id") ON DELETE CASCADE,
  "quantity" decimal(8,2) NOT NULL,
  "price" decimal(10,2) NOT NULL,
  "subtotal" decimal(15,2) NOT NULL,
  "created_at" timestamp with time zone DEFAULT now(),
  "updated_at" timestamp with time zone DEFAULT now()
);

-- Re-enable triggers



-- Data for users
INSERT INTO "users" ("id", "name", "email", "email_verified_at", "password", "role", "phone", "whatsapp", "address", "latitude", "longitude", "remember_token", "created_at", "updated_at") VALUES
(1, 'Administrator', 'admin@example.com', NULL, '$2y$04$BMZS4VvxmtcUP.pNTY73OO3GS8OMK5rrt62gEnFC1yI.HmTLdT2ju', 'admin', '081234567890', NULL, 'Jl. Laundry No. 1', NULL, NULL, NULL, '2026-04-02 09:41:52', '2026-04-26 14:12:50'),
(2, 'Pelanggan Setia', 'user@example.com', NULL, '$2y$04$gFo0uMC3AH6hNMTuysPbnum2B9WN2RNagzYnzgsmfV11DVK1tVGfq', 'user', '089876543210', NULL, 'Jl. Pelanggan No. 2', NULL, NULL, NULL, '2026-04-02 09:41:53', '2026-04-26 14:12:50'),
(3, 'rifa', 'rifa@coba.com', NULL, '$2y$04$gwalNYqqovM1AP3UUmeZG.mITmydbHc.DCTMgI6XQJy.e.Ig/b/5C', 'user', NULL, NULL, NULL, NULL, NULL, NULL, '2026-04-15 01:23:31', '2026-04-26 14:12:50'),
(4, 'febi', 'febi@gmail.com', NULL, '$2y$04$qfD20vAMdoqgoXeUIM874OMEkiDIPy4uifS2.ofbTcNOfJxNDPuzy', 'user', '0815423668585', NULL, NULL, NULL, NULL, NULL, '2026-04-17 02:26:32', '2026-05-02 14:54:55'),
(5, 'rif', 'rif12@gmail.com', NULL, '$2y$04$qSfRgRybszdslvGuFcwNS.Nesukzvt/ewl7dQmLDVq5JP9IosT9JO', 'user', NULL, NULL, NULL, NULL, NULL, NULL, '2026-04-25 18:28:11', '2026-04-26 14:12:50'),
(6, 'rifafauzi', 'rifa12@gmail.com', NULL, '$2y$04$bxZ1yR6qe.MPKaYOHxaBqO6n4P4TR/BhdMze7IxA1MLZG/G9euSRK', 'user', NULL, NULL, NULL, NULL, NULL, NULL, '2026-04-25 18:48:11', '2026-04-26 14:12:50'),
(7, 'rifafauzi', 'rifafauzi044@gmail.com', NULL, '$2y$04$6hCHNdVSlRoC.wnATm1imu4w.zr8MIyskL4FbVEMeTAegfUjdXYqe', 'user', '081223513917', NULL, NULL, NULL, NULL, NULL, '2026-05-02 03:30:51', '2026-05-02 03:30:51'),
(8, 'sela am', 'selaawaliyam25@gmail.com', NULL, '$2y$04$dDFtXv11lMRbSXs2T3N.X.ml9kA1btRCNDlOoVIQrfBOdpJvRXNte', 'user', '0852134691848', NULL, NULL, NULL, NULL, NULL, '2026-05-02 14:48:55', '2026-05-02 14:48:55');

-- Data for services
INSERT INTO "services" ("id", "name", "category", "price", "unit", "description", "created_at", "updated_at") VALUES
(1, 'Cuci Kiloan Standar', 'Kiloan', 6000.00, 'kg', NULL, '2026-04-02 09:41:53', '2026-04-02 09:41:53'),
(2, 'Cuci Kiloan Kilat', 'Kiloan', 10000.00, 'kg', NULL, '2026-04-02 09:41:53', '2026-04-02 09:41:53'),
(3, 'Cuci Selimut / Bedcover', 'Linen & Selimut', 25000.00, 'pcs', NULL, '2026-04-02 09:41:53', '2026-04-02 09:41:53'),
(4, 'Cuci Sepatu Premium', 'Sepatu & Tas', 35000.00, 'pasang', NULL, '2026-04-02 09:41:53', '2026-04-02 09:41:53'),
(5, 'Cuci + Setrika Kiloan', 'Kiloan', 8000.00, 'kg', 'Cuci bersih sekaligus disetrika rapi. Siap pakai!', '2026-04-22 12:56:12', '2026-04-22 12:56:12'),
(7, 'Cuci Bedcover / Selimut Tebal', 'Linen & Selimut', 25000.00, 'pcs', 'Bedcover, selimut tebal, sprei queen & king.', '2026-04-22 12:56:12', '2026-04-22 12:56:12'),
(8, 'Cuci Bantal /', 'Linen & Selimut', 10000.00, 'pcs', 'Bersih, fluffy, wangi seperti baru.', '2026-04-22 12:56:12', '2026-04-23 07:16:12'),
(9, 'Cuci Sepatu Standar', 'Sepatu & Tas', 20000.00, 'pasang', 'Sepatu kanvas, sneakers, olahraga.', '2026-04-22 12:56:12', '2026-04-22 12:56:12'),
(10, 'Cuci Tas', 'Sepatu & Tas', 30000.00, 'pcs', 'Tas kain, kanvas, ransel. Bersih & tidak merusak bahan.', '2026-04-22 12:56:12', '2026-04-22 12:56:12'),
(11, 'Setrika Saja (Kiloan)', 'Setrika', 4000.00, 'kg', 'Hanya setrika, tanpa cuci. Rapi & bebas kusut.', '2026-04-22 12:56:12', '2026-04-22 12:56:12'),
(12, 'Setrika Saja (Satuan)', 'Setrika', 3000.00, 'pcs', 'Per lembar pakaian, cocok untuk baju formal.', '2026-04-22 12:56:12', '2026-04-22 12:56:12'),
(13, 'baju', 'Umum', 6500.00, 'kg', NULL, '2026-04-23 07:15:39', '2026-04-23 07:15:39');

-- Data for transactions
INSERT INTO "transactions" ("id", "user_id", "invoice_code", "total_price", "status", "created_at", "updated_at", "address", "phone", "payment_method", "delivery_type") VALUES
(1, 2, 'INV-DUMMY123', 12000.00, 'selesai', '2026-04-02 09:42:21', '2026-04-09 14:41:34', NULL, NULL, NULL, NULL),
(2, 2, 'INV-LNDRYOK', 25000.00, 'selesai', '2026-04-02 09:42:21', '2026-04-02 09:42:21', NULL, NULL, NULL, NULL),
(3, 2, 'INV-20260409-92770', 7800.00, 'selesai', '2026-04-09 14:29:07', '2026-04-09 14:34:28', NULL, NULL, NULL, NULL),
(4, 2, 'INV-20260409-40FEA', 7800.00, 'selesai', '2026-04-09 14:29:08', '2026-04-09 14:42:32', NULL, NULL, NULL, NULL),
(5, 2, 'INV-20260410-9189C', 7500.00, 'baru', '2026-04-10 02:53:37', '2026-04-10 02:53:37', NULL, NULL, NULL, NULL),
(6, 4, 'INV-20260417-3D7C6', 23000.00, 'baru', '2026-04-17 02:30:17', '2026-04-17 02:30:17', NULL, NULL, NULL, NULL),
(7, 1, 'INV-69E4E95BA5431', 25000.00, 'baru', '2026-04-19 14:40:27', '2026-04-19 14:40:27', NULL, NULL, NULL, NULL),
(8, 4, 'INV-20260422-5765C', 168000.00, 'baru', '2026-04-22 15:29:30', '2026-04-22 15:29:30', NULL, NULL, NULL, NULL),
(9, 6, 'INV-20260425-27991', 54250.00, 'baru', '2026-04-25 18:50:33', '2026-04-25 18:50:33', NULL, NULL, NULL, NULL),
(10, 4, 'INV-20260426-2E53F', 4000.00, 'baru', '2026-04-26 15:32:32', '2026-04-26 15:32:32', NULL, NULL, NULL, NULL),
(11, 4, 'INV-20260426-8D523', 5000.00, 'baru', '2026-04-26 15:49:02', '2026-04-26 15:49:02', NULL, NULL, NULL, NULL),
(12, 4, 'INV-20260426-2AC95', 4000.00, 'baru', '2026-04-26 16:20:45', '2026-04-26 16:20:45', 'tut', '0857656', 'cash', 'antar_jemput'),
(13, 4, 'INV-20260501-A9602', 4000.00, 'baru', '2026-05-01 14:34:34', '2026-05-01 14:34:34', 'jhjjhhj', '08455656', 'cash', 'antar_jemput'),
(14, 1, 'INV-20260501-9B57A', 12000.00, 'baru', '2026-05-01 15:06:53', '2026-05-01 15:06:53', 'Test Address', 12345678, 'cash', 'antar_jemput'),
(15, 4, 'INV-20260501-BC445', 4000.00, 'baru', '2026-05-01 15:14:07', '2026-05-01 15:14:07', 'tt', '0765', 'cash', 'antar_jemput'),
(16, 4, 'INV-20260501-687DC', 10000.00, 'baru', '2026-05-01 15:23:31', '2026-05-01 15:23:31', 'rdhgf', '0r67', 'cash', 'antar_jemput'),
(17, 7, 'INV-20260502-22B88', 35000.00, 'selesai', '2026-05-02 03:32:06', '2026-05-02 03:36:32', 'Kp.Babakan Laksana', '081223513917', 'cash', 'bawa_sendiri'),
(18, 7, 'INV-20260502-69DAF', 3000.00, 'baru', '2026-05-02 03:37:26', '2026-05-02 03:37:26', 'kp babakan laksana', '081223513917', 'transfer', 'antar_jemput'),
(19, 7, 'INV-20260502-21A3C', 10000.00, 'diambil', '2026-05-02 03:49:18', '2026-05-02 07:59:15', 'hgcfh', '081223513917', 'transfer', 'antar_jemput'),
(20, 7, 'INV-20260502-98414', 25000.00, 'selesai', '2026-05-02 03:51:13', '2026-05-02 03:53:54', 'ewfreef', '081223513917', 'transfer', 'antar_jemput'),
(21, 4, 'INV-20260502-01243', 9000.00, 'baru', '2026-05-02 14:50:25', '2026-05-02 14:50:25', 'kp cikuya', '0821255458228', 'transfer', 'antar_jemput'),
(22, 4, 'INV-20260502-DCD70', 30000.00, 'baru', '2026-05-02 14:54:37', '2026-05-02 14:54:37', 'frbbbcd', '0824451635869', 'transfer', 'antar_jemput');

-- Data for transaction_details
INSERT INTO "transaction_details" ("id", "transaction_id", "service_id", "quantity", "price", "subtotal", "created_at", "updated_at") VALUES
(1, 1, 1, 2.00, 6000.00, 12000.00, '2026-04-02 09:42:21', '2026-04-02 09:42:21'),
(2, 2, 3, 1.00, 25000.00, 25000.00, '2026-04-02 09:42:21', '2026-04-02 09:42:21'),
(3, 3, 1, 1.30, 6000.00, 7800.00, '2026-04-09 14:29:07', '2026-04-09 14:29:07'),
(4, 4, 1, 1.30, 6000.00, 7800.00, '2026-04-09 14:29:08', '2026-04-09 14:29:08'),
(5, 5, 2, 0.50, 10000.00, 5000.00, '2026-04-10 02:53:37', '2026-04-10 02:53:37'),
(6, 5, 3, 0.10, 25000.00, 2500.00, '2026-04-10 02:53:37', '2026-04-10 02:53:37'),
(7, 6, 2, 0.40, 10000.00, 4000.00, '2026-04-17 02:30:17', '2026-04-17 02:30:17'),
(8, 6, 2, 1.90, 10000.00, 19000.00, '2026-04-17 02:30:17', '2026-04-17 02:30:17'),
(9, 7, 1, 2.50, 6000.00, 15000.00, '2026-04-19 14:40:27', '2026-04-19 14:40:27'),
(10, 7, 2, 1.00, 10000.00, 10000.00, '2026-04-19 14:40:27', '2026-04-19 14:40:27'),
(11, 8, 1, 3.00, 6000.00, 18000.00, '2026-04-22 15:29:30', '2026-04-22 15:29:30'),
(12, 8, 3, 6.00, 25000.00, 150000.00, '2026-04-22 15:29:30', '2026-04-22 15:29:30'),
(13, 9, 5, 0.50, 8000.00, 4000.00, '2026-04-25 18:50:33', '2026-04-25 18:50:33'),
(14, 9, 8, 1.00, 10000.00, 10000.00, '2026-04-25 18:50:33', '2026-04-25 18:50:33'),
(15, 9, 4, 1.00, 35000.00, 35000.00, '2026-04-25 18:50:33', '2026-04-25 18:50:33'),
(16, 9, 11, 0.50, 4000.00, 2000.00, '2026-04-25 18:50:33', '2026-04-25 18:50:33'),
(17, 9, 13, 0.50, 6500.00, 3250.00, '2026-04-25 18:50:33', '2026-04-25 18:50:33'),
(18, 10, 5, 0.50, 8000.00, 4000.00, '2026-04-26 15:32:32', '2026-04-26 15:32:32'),
(19, 11, 2, 0.50, 10000.00, 5000.00, '2026-04-26 15:49:02', '2026-04-26 15:49:02'),
(20, 12, 5, 0.50, 8000.00, 4000.00, '2026-04-26 16:20:45', '2026-04-26 16:20:45'),
(21, 13, 5, 0.50, 8000.00, 4000.00, '2026-05-01 14:34:34', '2026-05-01 14:34:34'),
(22, 14, 1, 2.00, 6000.00, 12000.00, '2026-05-01 15:06:53', '2026-05-01 15:06:53'),
(23, 15, 5, 0.50, 8000.00, 4000.00, '2026-05-01 15:14:07', '2026-05-01 15:14:07'),
(24, 16, 8, 1.00, 10000.00, 10000.00, '2026-05-01 15:23:31', '2026-05-01 15:23:31'),
(25, 17, 4, 1.00, 35000.00, 35000.00, '2026-05-02 03:32:06', '2026-05-02 03:32:06'),
(26, 18, 1, 0.50, 6000.00, 3000.00, '2026-05-02 03:37:26', '2026-05-02 03:37:26'),
(27, 19, 8, 1.00, 10000.00, 10000.00, '2026-05-02 03:49:18', '2026-05-02 03:49:18'),
(28, 20, 3, 1.00, 25000.00, 25000.00, '2026-05-02 03:51:13', '2026-05-02 03:51:13'),
(29, 21, 5, 0.50, 8000.00, 4000.00, '2026-05-02 14:50:25', '2026-05-02 14:50:25'),
(30, 21, 2, 0.50, 10000.00, 5000.00, '2026-05-02 14:50:25', '2026-05-02 14:50:25'),
(31, 22, 10, 1.00, 30000.00, 30000.00, '2026-05-02 14:54:37', '2026-05-02 14:54:37');

SET session_replication_role = 'origin';
