-- Supabase Schema for Rumah Laundry (No Records)
-- Run this in Supabase SQL Editor first

-- Disable triggers and foreign key constraints temporarily
SET session_replication_role = 'replica';

-- Drop existing tables
DROP TABLE IF EXISTS "transaction_details" CASCADE;
DROP TABLE IF EXISTS "transactions" CASCADE;
DROP TABLE IF EXISTS "services" CASCADE;
DROP TABLE IF EXISTS "users" CASCADE;

-- Table structure for users
CREATE TABLE "users" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "name" text NOT NULL,
  "email" text NOT NULL UNIQUE,
  "email_verified_at" timestamp with time zone NULL,
  "password" text NOT NULL,
  "role" text NOT NULL DEFAULT 'user',
  "phone" text NULL,
  "whatsapp" text NULL,
  "address" text NULL,
  "latitude" decimal(10,7) NULL,
  "longitude" decimal(10,7) NULL,
  "remember_token" text NULL,
  "created_at" timestamp with time zone DEFAULT now(),
  "updated_at" timestamp with time zone DEFAULT now()
);

-- Table structure for services
CREATE TABLE "services" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "name" text NOT NULL,
  "category" text NOT NULL DEFAULT 'Umum',
  "price" decimal(10,2) NOT NULL,
  "unit" text NOT NULL DEFAULT 'kg',
  "description" text NULL,
  "created_at" timestamp with time zone DEFAULT now(),
  "updated_at" timestamp with time zone DEFAULT now()
);

-- Table structure for transactions
CREATE TABLE "transactions" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "user_id" bigint NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
  "invoice_code" text NOT NULL UNIQUE,
  "total_price" decimal(15,2) NOT NULL DEFAULT 0.00,
  "status" text NOT NULL DEFAULT 'baru',
  "address" text NULL,
  "phone" text NULL,
  "payment_method" text NULL,
  "delivery_type" text NULL,
  "created_at" timestamp with time zone DEFAULT now(),
  "updated_at" timestamp with time zone DEFAULT now(),
  CONSTRAINT "transactions_status_check" CHECK ("status" IN ('baru','cuci','kering','setrika','selesai','diambil'))
);

-- Table structure for transaction_details
CREATE TABLE "transaction_details" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "transaction_id" bigint NOT NULL REFERENCES "transactions"("id") ON DELETE CASCADE,
  "service_id" bigint NOT NULL REFERENCES "services"("id") ON DELETE CASCADE,
  "quantity" decimal(8,2) NOT NULL,
  "price" decimal(10,2) NOT NULL,
  "subtotal" decimal(15,2) NOT NULL,
  "created_at" timestamp with time zone DEFAULT now(),
  "updated_at" timestamp with time zone DEFAULT now()
);

-- Re-enable triggers
SET session_replication_role = 'origin';
